{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: default-ingress
  namespace: {{ .Values.nameSpace }}
  labels:
    {{- include "k8s.labels" . | nindent 8 }}
spec:
  rules:
  - host: "api.example.com"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ .Values.djangoCore.name }}-service
            port:
              number: 8000
  - host: "flower.example.com"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ .Values.djangoCelery.flower.name }}-service
            port:
              number: 5555
{{- end }}