apiVersion: apps/v1
kind: Deployment
metadata:
    namespace: {{ .Values.nameSpace }}
    name: {{ .Values.djangoCelery.beat.name }}
    labels:
        app: {{ .Values.djangoCelery.beat.name }}
        {{- include "k8s.labels" . | nindent 8 }}
spec:
    replicas: 1
    selector:
        matchLabels:
            pod: {{ .Values.djangoCelery.beat.name }}-pod
    template:
        metadata:
            labels:
                pod: {{ .Values.djangoCelery.beat.name }}-pod
        spec:
            containers:
                - name: celery-beat
                  image: {{ .Values.django.container.name }}
                  command: ["celery", "-A", "backend", "beat", "-l", "info"]
                  resources:
                        requests:
                            cpu: "100m"
                            memory: "100Mi"
                  env:          
                    {{- range $key, $val := .Values.env }}
                      - name: {{ $key }}
                        value: {{ $val | quote }}
                    {{- end }}
                  envFrom:
                      - configMapRef:
                            name: {{ .Values.configMap.name }}
