apiVersion: apps/v1
kind: Deployment
metadata:
    namespace: {{ .Values.nameSpace }}
    name: {{ .Values.djangoCelery.workerDefault.name }}
    labels:
        deployment: {{ .Values.djangoCelery.workerDefault.name }}
        {{- include "k8s.labels" . | nindent 8 }}
spec:
    replicas: 1
    selector:
        matchLabels:
            pod: {{ .Values.djangoCelery.workerDefault.name }}-pod
    template:
        metadata:
            labels:
                pod: {{ .Values.djangoCelery.workerDefault.name }}-pod
        spec:
            containers:
                - name: celery-worker
                  image: {{ .Values.django.container.name }}
                  command:
                      [
                          "celery",
                          "-A",
                          "backend",
                          "worker",
                          "-l",
                          "info",
                      ]
                  resources:
                        requests:
                            cpu: "100m"
                            memory: "150Mi"
                  env:          
                    {{- range $key, $val := .Values.env }}
                      - name: {{ $key }}
                        value: {{ $val | quote }}
                    {{- end }}
                  envFrom:
                      - configMapRef:
                            name: {{ .Values.configMap.name }}
