apiVersion: batch/v1
kind: Job
metadata:
    namespace: {{ .Values.nameSpace }}
    name:  {{ .Values.djangoMigrationsJob.name }}-job
    labels:
        {{- include "k8s.labels" . | nindent 8 }}
spec:
    ttlSecondsAfterFinished: 30
    template:
        spec:
            containers:
                - name: django
                  image: {{ .Values.django.container.name}}
                  command: ["python", "manage.py", "migrate", "--noinput"]
                  resources:
                        requests:
                            cpu: "100m"
                            memory: "150Mi"
                  env:          
                    {{- range $key, $val := .Values.env }}
                      - name: {{ $key }}
                        value: {{ $val | quote }}
                    {{- end }}
                  envFrom:
                      - configMapRef:
                            name: {{ .Values.configMap.name}}

            restartPolicy: Never
    backoffLimit: 5
