# docker-compose -f docker-compose-services.yml up
# can be extended https://docs.docker.com/compose/extends/

version: "3.3"

services:
  core-redis:
    restart: always
    image: redis:latest
    depends_on:
      - core-postgres # hack to ensure core-postgres is ready by the time django starts
      - core-pgbouncer # hack to ensure core-postgres is ready by the time django starts
    volumes:
      - core-redisdata:/data

  core-postgres:
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data/

  core-pgbouncer:
    image: edoburu/pgbouncer
    environment:
      - DB_HOST=core-postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
      - POOL_MODE=transaction
      # - ADMIN_USERS=postgres
      - AUTH_TYPE=plain
    #    ports:
    #      - "5432:5432"
    depends_on:
      - core-postgres

  core-pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"

  core-webhook-tester:
    image: tarampampam/webhook-tester:latest
    ports:
      - "8080:8080"
    environment:
      - LISTEN_PORT=8080
      - REDIS_DSN=redis://core-redis:6379/0
    command: serve

volumes:
  pgdata:
  core-redisdata:
  flowerdata:
