apiVersion: v1
kind: Service
metadata:
    namespace: {{ .Values.nameSpace }}
    name: {{ .Values.djangoCelery.flower.name }}-service
    labels:
        {{- include "k8s.labels" . | nindent 8 }}
spec:
    selector:
        pod: {{ .Values.djangoCelery.flower.name }}-pod
    ports:
        - port: 5555
    type: {{ .Values.defaultServiceExposure }}
    # type: NodePort
